configfile: "../../config.yaml"

subworkflow genesets:
    workdir: "../genesets"
    snakefile: "../genesets/Snakefile"

rule all:
    input:
        expand("{dsets}/{sets}.rds", dsets=['gdsc', 'ccle'], sets=config['genesets'])

rule gdsc:
    input:
        rscript = "{dset}.r",
        setfile = genesets("human/{sets}.RData")
    output:
        outfile = "{dset}/{sets}.rds"
    resources:
        walltime = 60,
        mem = 4096
    shell:
        "Rscript {input.rscript}"
            " --setfile {input.setfile}"
            " --outfile {output.outfile}"
