rule mad2_transposon:
    input:
        rscript = "assemble.r",
        samples = "samples.tsv",
        reads = "PB170929_raw_readcount_dedup_UMIs.txt"
    output:
        result = "assemble.RData"
    shell:
        "Rscript {input.rscript}"
