genesets:
    - KEA_2015
    - GO_Biological_Process_2018
    - GO_Cellular_Component_2018
    - GO_Molecular_Function_2018
    - ENCODE_and_ChEA_Consensus_TFs_from_ChIP-X
    - Reactome_2016
    - KEGG_2016
    - TargetScan_microRNA_2017
    - MSigDB_Oncogenic_Signatures
    - CH.HALLMARK

ins_plots: [ Erg, Ets1, Arid2, Drg1, Crebbp, Xrcc6, Trp53,
    Ikzf1, Pten, Suz12, Notch1, Rapgef6, Nf1 ]
