subworkflow rnaseq:
    workdir: "../../data/rnaseq"

rule all:
    input:
        expand("ploidy_{type}.{ext}",
                type=['eT', 'both', 'cancer_only'],
                ext=['RData', 'pdf'])

rule no_deps:
    input:
        rscript = "{type}.r"
    output:
        result = "{type}.RData",
        plot = "{type}.pdf"
    shell:
        "Rscript {input.rscript}"

rule eT:
    input:
        rscript = "ploidy_eT.r",
        mad2_rna = rnaseq("assemble.RData"),
        tall = "../../data/rnaseq/T-ALL_read_count.txt"
    output:
        result = "ploidy_eT.RData",
        plot = "ploidy_eT.pdf"
    shell:
        "Rscript {input.rscript}"

rule cancer_only:
    input:
        rscript = "ploidy_cancer_only.r"
    output:
        result = "ploidy_cancer_only.RData",
        plot = "ploidy_cancer_only.pdf"
    shell:
        "Rscript {input.rscript}"

rule both:
    input:
        rscript = "ploidy_both.r"
    output:
        result = "ploidy_both.RData",
        plot = "ploidy_both.pdf"
    shell:
        "Rscript {input.rscript}"
