#rule transposon_seq:
#    input:
#        genbank = "pA6-GrOnc.gb"
#    output:
#        fasta = "pA6-GrOnc.fasta"
#        features = "pA6-GrOnc.tsv"
#    run:
#        """
#        from Bio import SeqIO
#        SeqIO.convert({input.genbank}, "genbank", {output.fasta}, "fasta")
#        """

rule combined_ref:
    input:
        fasta = "../genome/Mus_musculus.GRCm38.dna_rm.toplevel.fa",
        gtf = "../genome/Mus_musculus.GRCm38.92.gtf",
        transposon_fasta = "pA6-GrOnc.fasta",
        transposon_feats = "pA6-GrOnc.tsv"
    output:
        genome = "STAR_GRCm38_ens92_PB"
    shell:
        "imfusion-build star"
            " --reference_seq {input.fasta}"
            " --reference_gtf {input.gtf}"
            " --transposon_seq {input.transposon_fasta}"
            " --transposon_features {input.transposon_feats}"
            " --output_dir {output.genome}"
            " --blacklist_genes ENSMUSG00000039095 ENSMUSG00000038402"
