rule all:
    input:
        "E-GEOD-13159.rds", "E-GEOD-28497.rds"

rule dataset:
    input:
        rscript = "process.r"
    output:
        outfile = "{accession}.rds"
    resources:
        mem = 61440,
        walltime = 4200
    shell:
        "Rscript {input.rscript}"
            " --accession {wildcards.accession}"
            " --summarize ensembl_gene_id"
            " --outfile {output.outfile}"
