rule all:
    input:
        "E-GEOD-13159.RData", "E-GEOD-28497.RData"

rule dataset:
    input:
        rscript = "process.r"
    output:
        outfile = "{accession}.RData"
    resources:
        mem = 204800,
        walltime = 4200
    shell:
        "Rscript {input.rscript}"
            " --accession {wildcards.accession}"
            " --summarize ensembl_gene_id"
            " --outfile {output.outfile}"
