subworkflow rnaseq:
    workdir: "../rnaseq"
    snakefile: "../rnaseq/Snakefile"

rule all:
    input:
        "meta.RData"

rule meta:
    input:
        rscript = "meta.r",
        xlsx = "Final table mice.xlsx",
    output:
        tsv = "meta.tsv"
    shell:
        "Rscript {input.rscript} --infile '{input.xlsx}' --outfile {output.tsv}"
