subworkflow ploidy:
    workdir: "../ploidy_compare"

rule all:
    input:
        "meta.tsv"

rule meta:
    input:
        rscript = "meta.r",
        xlsx = "TPS_screen_MasterList.xlsx"
    output:
        outfile = "meta.rds"
    shell:
        "Rscript {input.rscript} --infile '{input.xlsx}' --outfile {output.outfile}"

rule aset:
    input:
        rscript = "meta.r",
        xlsx = "TPS_screen_MasterList.xlsx",
        aneup = ploidy("analysis_set.rds")
    output:
        tsv = "meta_aset.tsv"
    shell:
        "Rscript {input.rscript} --infile '{input.xlsx}' --outfile {output.tsv}"
