configfile: "../config.yaml"

subworkflow stat_ko:
    workdir: "../data/rnaseq_stat1"
    snakefile: "../data/rnaseq_stat1"

subworkflow sets:
    workdir: "../data/genesets"
    snakefile: "../data/genesets/Snakefile"

rule all:
    input:
        expand("diff_expr/{sets}.pdf", sets=config['genesets']),
        "stat1ko_diff_inflamm_resp.pdf"

rule de_genes:
    input:
        rscript = "diff_expr.r",
        dset = stat_ko("dset.rds")
    output:
        outfile = "diff_expr.rds",
        plotfile = "diff_expr.pdf"
    shell:
        "Rscript {input.rscript}"
            " --dset {input.dset}"
            " --outfile {output.outfile}"
            " --plotfile {output.plotfile}"

rule de_sets:
    input:
        rscript = "de_sets.r",
        diff_expr = "diff_expr.rds",
        setfile = lambda wc: sets("human/{sets}.RData")
    output:
        plotfile = "diff_expr/{sets}.pdf"
    shell:
        "Rscript {input.rscript}"
            " --diff_expr {input.diff_expr}"
            " --setfile {input.setfile}"
            " --plotfile {output.plotfile}"

rule stat1ko_inflamm:
    input:
        rscript = "stat1ko_diff_inflamm_resp.r",
        de_gene = "diff_expr.rds",
        setfile = sets("human/CH.HALLMARK.RData")
    output:
        plotfile = "stat1ko_diff_inflamm_resp.pdf"
    shell:
        "Rscript {input.rscript}"
            " --diff_expr {input.de_gene}"
            " --setfile {input.setfile}"
            " --plotfile {output.plotfile}"
