rule all:
    input:
        expand("ploidy_{type}.{ext}",
                type=['eT', 'both', 'cancer_only'],
                ext=['RData', 'pdf'])

rule no_deps:
    input:
        rscript = "{type}.r"
    output:
        result = "{type}.RData",
        plot = "{type}.pdf"
    shell:
        "Rscript {input.rscript}"

rule cancer_ploidy:
    input:
        rscript = "ploidy_cancer_only.r"
    output:
        result = "ploidy_cancer_only.RData",
        plot = "ploidy_cancer_only.pdf"
    shell:
        "Rscript {input.rscript}"

rule both:
    input:
        rscript = "ploidy_both.r"
    output:
        result = "ploidy_both.RData",
        plot = "ploidy_both.pdf"
    shell:
        "Rscript {input.rscript}"
