configfile: "../../config.yaml"

rule all:
    input:
        expand("{geneset}.RData", geneset=config['genesets'])

rule enrichr:
    input:
        rscript = "make_set.r"
    output:
        "{geneset}.RData"
    shell:
        "Rscript {input.rscript} --geneset {wildcards.geneset} --outfile {output}"
