configfile: "../../config.yaml"

subworkflow sets:
    workdir: "../genesets"
    snakefile: "../genesets/Snakefile"

rule all:
    input:
        expand("sets/{sets}.pdf", sets=config['genesets'])

rule dset:
    input:
        rscript = "dset.r",
        yaml = "BT549_Stat1.yaml",
        expr = "count_matrix_known_barcodes_STL_and_USS_genes.txt"
    output:
        outfile = "dset.rds",
        plotfile = "dset.pdf"
    shell:
        "Rscript {intput.rscript}"
            " --yaml {input.yaml}"
            " --expr {input.expr}"
            " --outfile {output.outfile}"
            " --plotfile {output.plotfile}"

rule de_genes:
    input:
        rscript = "diff_expr.r",
        dset = "dset.rds"
    output:
        outfile = "diff_expr.rds",
        plotfile = "diff_expr.pdf"
    shell:
        "Rscript {input.rscript}"
            " --dset {input.dset}"
            " --outfile {output.outfile}"
            " --plotfile {output.plotfile}"

rule de_sets:
    input:
        rscript = "de_sets.r",
        diff_expr = "diff_expr.rds",
        setfile = lambda wc: sets("human/{sets}.RData")
    output:
        plotfile = "sets/{sets}.pdf"
    shell:
        "Rscript {input.rscript}"
            " --diff_expr {input.diff_expr}"
            " --setfile {input.setfile}"
            " --plotfile {output.plotfile}"
