models = ['logit', 'logit-adjNins', 'betareg', 'betareg_1clonal',
          'lm', 'lm_1clonal', 'gamma', 'gamma_adjNins', 'gamma2', 'ks']
types = ['hits', 'hits_cancer', 'near', 'near_cancer']

rule all:
    input:
        expand("{model}-{type}.pdf", model=models, type=types)

rule dset:
    input:
        rscript = "dset_merge.r"
    output:
        dset = "dset.RData"
    shell:
        "Rscript {input.rscript}"

rule models:
    input:
        rscript = "{model}.r",
        dset = "dset.RData"
    output:
        fits = "{model}.RData"
    resources:
        walltime = 600
    shell:
        "Rscript {input.rscript}"
            " --samples 5" # gene w/ at least 5 inserts to consider
            " --outfile {output.fits}"

rule plot:
    input:
        rscript = "plot.r",
        assocs = "{assocs}.RData"
    output:
        plot = "{assocs}-{type}.pdf"
    shell:
        "Rscript {input.rscript}"
            " --assocs {input.assocs}"
            " --subset {wildcards.type}"
            " --plotfile {output.plot}"
