rule all:
    input:
        expand("{dset}.pdf", dset=['gdsc', 'ccle'])

rule plot:
    input:
        rscript = "{dset}.r",
        highlight = "highlight.yaml",
        dset = "{dset}.yaml"
    output:
        plotfile = "{dset}.pdf"
    shell:
        "Rscript {input.rscript}"
            " --highlight {input.highlight}"
            " --dset {input.dset}"
            " --plotfile {output.plotfile}"
