configfile: "../config.yaml"

subworkflow sets:
    workdir: "../data/genesets"
    snakefile: "../data/genesets/Snakefile"

subworkflow expr_diff:
    workdir: "../expr_diff"
    snakefile: "../expr_diff/Snakefile"

subworkflow expr_stat1:
    workdir: "../expr_stat1"
    snakefile: "../expr_stat1/Snakefile"

infiles = {
    'EtsErg' : expr_diff('de_Mad2PB+EtsErg.RData'),
    'myc' : sets('human/CH.HALLMARK.RData'),
    'statKO' : expr_stat1('diff_expr.rds')
}

rule all:
    input:
        expand("sig_{sig}.rds", sig=infiles.keys())

rule sigs:
    input:
        rscript = "sig_{sig}.r",
        infile = lambda wc: infiles[wc.sig]
    output:
        outfile = "sig_{sig}.rds"
    shell:
        "Rscript {input.rscript}"
            " --infile {input.infile}"
            " --outfile {output.outfile}"
