dirs = ["FCS files - part 1", "FCS files - part 2"]

rule all:
    input:
        expand("{dir}.pdf", dir=dirs)

rule dset:
    input:
        rscript = "dset.r"
    output:
        outfile = "{dir}.rds"
    shell:
        "Rscript {input.rscript}"
            " --dir '{wildcards.dir}'"
            " --outfile '{output.outfile}'"

rule plot:
    input:
        rscript = "plot.r",
        infile = "{dir}.rds"
    output:
        plotfile = "{dir}.pdf"
    shell:
        "Rscript {input.rscript}"
            " --infile '{input.infile}'"
            " --plotfile '{output.plotfile}'"
