subworkflow meta:
    workdir: "../meta"

dirs = ["FCS files - part 1", "FCS files - part 2"]

rule all:
    input:
        expand("{dir}.pdf", dir=dirs),
        "summarize.pdf"

rule dset:
    input:
        rscript = "dset.r"
    output:
        outfile = "{dir}.rds"
    shell:
        "Rscript {input.rscript}"
            " --dir '{wildcards.dir}'"
            " --outfile '{output.outfile}'"

rule plot:
    input:
        rscript = "plot.r",
        infile = "{dir}.rds"
    output:
        plotfile = "{dir}.pdf"
    shell:
        "Rscript {input.rscript}"
            " --infile '{input.infile}'"
            " --plotfile '{output.plotfile}'"

rule summarize:
    input:
        rscript = "summarize.r",
        meta = meta("meta.tsv"),
        infiles = expand("{dir}.rds", dir=dirs)
    output:
        outfile = "summarize.rds",
        plotfile = "summarize.pdf"
    shell:
        "Rscript {input.rscript}"
            " --outfile {output.outfile}"
            " --plotfile {output.plotfile}"
#            " {input.infiles}" # missing quotes around each file name
