import os
from glob import glob
files = glob("**/*.yaml", recursive=True)
fstem = [os.path.splitext(p)[0] for p in files]

rule all:
    input:
        expand("{sample}.RData", sample=fstem),
        expand("{sample}.pdf", sample=fstem)

rule samples:
    input:
        samples = "{sample}.yaml",
        diploid_ref = "GRCm38_diploid_ref.bam"
    output:
        model = "{sample}.RData",
        plot = "{sample}.pdf"
    shell:
        "Rscript /data/p282396/ebits/tools/aneufinder/__init__.r"
            " --outfile {output.model}"
            " --plotfile {output.plot}"
            " --min_reads 1e5"
            " {input.samples}"

rule diploid_ref:
    input:
        mouse = expand("seqdata/180309_NB501840_0059_AHLFNMBGX5/LJ180205_I/{bam}",
                bam = ["LJ180205_I_001.bam", "LJ180205_I_002.bam"])
    output:
        mouse = "GRCm38_diploid_ref.bam"
    shell:
        "samtools merge {output.mouse} {input.mouse}; "
        "samtools index {output.mouse}; "
