subworkflow meta:
    workdir: "../meta"
    snakefile: "../meta/Snakefile"

import os
from glob import glob
files = glob("**/*.yaml", recursive=True)
fstem = [os.path.splitext(p)[0] for p in files]

rule all:
    input:
        "30cellseq.RData",
        "sc_merge.RData",
        expand("{sample}.RData", sample=fstem),
        expand("{sample}.pdf", sample=fstem)

rule assemble_single:
    input:
        rscript = "sc_merge.r",
        data = expand("{sample}.RData", sample=['401t', '419t', '413s'])
    output:
        merged = "sc_merge.RData"
    shell:
        "Rscript {input.rscript} --outfile {output.merged} {input.data}"

rule assemble_thirty:
    input:
        rscript = "30cellseq.r",
        data = expand("30cellseq_batch{batch}.RData", batch=[1,2])
    output:
        merged = "30cellseq.RData",
        plot = "30cellseq.pdf"
    shell:
        "Rscript {input.rscript}"
            " --outfile {output.merged}"
            " --plotfile {output.plot}"
            " {input.data}"

rule samples:
    input:
        samples = "{sample}.yaml",
        diploid_ref = "GRCm38_diploid_ref.bam"
    output:
        model = "{sample}.RData",
        plot = "{sample}.pdf"
    resources:
        mem = 10240
    shell:
        "Rscript /data/p282396/ebits/tools/aneufinder/__init__.r"
            " --outfile {output.model}"
            " --plotfile {output.plot}"
            " --min_reads 1e5"
            " {input.samples}"

rule diploid_ref:
    input:
        mouse = expand("seqdata/180309_NB501840_0059_AHLFNMBGX5/LJ180205_I/{bam}",
                bam = ["LJ180205_I_001.bam", "LJ180205_I_002.bam"])
    output:
        mouse = "GRCm38_diploid_ref.bam"
    shell:
        "samtools merge {output.mouse} {input.mouse}; "
        "samtools index {output.mouse}; "
