rule all:
    input:
        "diff_expr.pdf"

rule plot:
    input:
        rscript = "plot.r",
        diff_expr = "diff_expr.rds"
    output:
        plotfile = "diff_expr.pdf"
    shell:
        "Rscript {input.rscript}"
            " --diff_expr {input.diff_expr}"
            " --plotfile {output.plotfile}"

rule diff_expr:
    input:
        rscript = "diff_expr.r",
        comps = "diff_expr.yaml",
        eset = "samples.rds"
    output:
        outfile = "diff_expr.rds",
    shell:
        "Rscript {input.rscript}"
            " --eset {input.eset}"
            " --comps {input.comps}"
            " --outfile {output.outfile}"

rule eset:
    input:
        rscript = "samples.r",
        samples = "samples.tsv",
        infile = "count_matrix_known_barcodes_STL_and_USS_genes.txt.gz"
    output:
        outfile = "samples.rds",
        plotfile = "samples.pdf"
    shell:
        "Rscript {input.rscript}"
            " --infile {input.infile}"
            " --samples {input.samples}"
            " --outfile {output.outfile}"
            " --plotfile {output.plotfile}"
