rule all:
    input:
        expand("{yaml}.pdf", yaml=["cell_lines", "tumors"])

rule plot:
    input:
        rscript = "plot.r",
        diff_expr = "{yaml}.rds"
    output:
        plotfile = "{yaml}.pdf"
    shell:
        "Rscript {input.rscript}"
            " --diff_expr {input.diff_expr}"
            " --plotfile {output.plotfile}"

rule diff_expr:
    input:
        rscript = "diff_expr.r",
        comps = "{yaml}.yaml",
        eset = "samples.rds"
    output:
        outfile = "{yaml}.rds"
    shell:
        "Rscript {input.rscript}"
            " --eset {input.eset}"
            " --comps {input.comps}"
            " --outfile {output.outfile}"

rule eset:
    input:
        rscript = "samples.r",
        samples = "samples.tsv",
        infile = "count_matrix_known_barcodes_STL_and_USS_genes.txt.gz"
    output:
        outfile = "samples.rds",
        plotfile = "samples.pdf"
    shell:
        "Rscript {input.rscript}"
            " --infile {input.infile}"
            " --samples {input.samples}"
            " --outfile {output.outfile}"
            " --plotfile {output.plotfile}"
