configfile: "../config.yaml"

subworkflow genesets:
    workdir: "../data/genesets"
    snakefile: "../data/genesets/Snakefile"

subworkflow network:
    workdir: "../data/networks"
    snakefile: "../data/networks/Snakefile"

subworkflow gsva:
    workdir: "../expr_sets"
    snakefile: "../expr_sets/Snakefile"

expr = {
    'mile' : '../data/arrayexpress/E-GEOD-13159.RData',
    'mile2' : '../expr_diff/eset_MILE.RData',
    'mad2pb' : '../data/rnaseq/assemble.RData'
}

rule all:
    input:
        expand("genenet-{kind}_{expr}.pdf", kind=['genes', 'sets'],
                expr=['mad2pb', 'mile']),
        expand("viper-{expr}.pdf", expr=expr.keys())

rule genenet:
    input:
        rscript = "genenet.r",
        expr = gsva("{kind}_{expr}.RData")
    output:
        plot = "genenet-{kind}_{expr}.pdf"
    resources:
        mem = 10240,
        walltime = 240
    shell:
        "Rscript {input.rscript}"
            " --expr {input.expr}"
            " --plotfile {output.plot}"

rule viper:
    input:
        rscript = "viper.r",
        expr = lambda wc: expr[wc.expr],
        net = network("E-GEOD-13159.RData")
    output:
        plot = "viper-{expr}.pdf"
    resources:
        mem = 10240,
        walltime = 240
    shell:
        "Rscript {input.rscript}"
            " --expr {input.expr}"
            " --network {input.net}"
            " --plotfile {output.plot}"
