configfile: "../../config.yaml"

subworkflow genesets:
    workdir: "../genesets"
    snakefile: "../genesets/Snakefile"

rule all:
    input:
        expand("{dsets}/{sets}.rds", dsets=['gdsc', 'ccle', 'tcga'], sets=config['genesets'])

rule gsva:
    input:
        rscript = "{dset}.r",
        setfile = genesets("human/{sets}.rds")
    output:
        outfile = "{dset}/{sets}.rds"
    threads: 12
    resources:
        walltime = 60,
        mem = 10240
    shell:
        "Rscript {input.rscript}"
            " --setfile {input.setfile}"
            " --threads {threads}"
            " --outfile {output.outfile}"
