configfile: "../../config.yaml"

subworkflow genesets:
    workdir: "../genesets"

def gs(wc):
    org = "human"
    if wc.dset == "mad2pb":
        org = "mouse"
    return org + "/" + wc.sets + ".rds"

dsets = [ 'gdsc', 'ccle', 'tcga-brca', 'mad2pb' ]

rule all:
    input:
        expand("{dset}/{sets}.rds", dset=dsets, sets=config['genesets'] + ['stat1_ko'])

rule gsva:
    input:
        rscript = "{dset}.r",
        setfile = lambda wc: genesets(gs(wc))
    output:
        outfile = "{dset}/{sets}.rds"
    threads: 12
    resources:
        walltime = 60,
        mem = 10240
    shell:
        "Rscript {input.rscript}"
            " --setfile {input.setfile}"
            " --threads {threads}"
            " --outfile {output.outfile}"
