subworkflow rnaseq:
    workdir: "../data/rnaseq"

rule all:
    input:
        "panel_ploidy.rds",
        "eT_ploidy.rds",
        "violin_compare.pdf"

rule violin:
    input:
        rscript = "violin_compare.r"
    output:
        plot  = "violin_compare.pdf"
    shell:
        "Rscript {input.rscript}"

rule panel:
    input:
        rscript = "panel_ploidy.r",
        rnaseq = rnaseq("assemble.rds")
    output:
        result = "panel_ploidy.rds"
    shell:
        "Rscript {input.rscript}"

rule eT:
    input:
        rscript = "eT_ploidy.r",
        rnaseq = rnaseq("assemble.rds"),
        eT = rnaseq("Mad2+p53_batch2.rds")
    output:
        result = "eT_ploidy.rds"
    shell:
        "Rscript {input.rscript}"
