subworkflow rnaseq:
    workdir: "../data/rnaseq"
    snakefile: "../data/rnaseq/Snakefile"

rule all:
    input:
        "panel_ploidy.RData",
        "eT_ploidy.RData",
        "violin_compare.pdf"

rule violin:
    input:
        rscript = "violin_compare.r"
    output:
        plot  = "violin_compare.pdf"
    shell:
        "Rscript {input.rscript}"

rule panel:
    input:
        rscript = "panel_ploidy.r",
        rnaseq = rnaseq("assemble.RData")
    output:
        result = "panel_ploidy.RData",
        plot  = "panel_ploidy.pdf"
    resources:
        walltime = 7200
    shell:
        "Rscript {input.rscript}"

rule eT:
    input:
        rscript = "eT_ploidy.r",
        rnaseq = rnaseq("assemble.RData"),
        eT = "../tis_rna-ploidy_cis-fet/compare_rna-scWGS_ploidy/ploidy_eT.RData"
    output:
        result = "eT_ploidy.RData",
        plot  = "eT_ploidy.pdf"
    resources:
        walltime = 7200
    shell:
        "Rscript {input.rscript}"
