rule all:
    input:
        expand("Ets1+Erg_{set}.pdf", set=['gdsc', 'mad2pb', 'mile'])

rule plot:
    input:
        rscript = "{script}.r"
    output:
        plot = "Ets1+Erg_{script}.pdf"
    shell:
        "Rscript {input.rscript} --plotfile {output.plot}"
